
CREATE TABLE your_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data VARCHAR(255),
    version INT
);


-- Insertion de données initiales
--INSERT INTO data_entity ( data, version) VALUES ('Donnée 1', 2);
--INSERT INTO data_entity ( data, version) VALUES ('Donnée 2', 1);
